test_project:
  outputs:
    dev:
      account: VGRPLGU-EJ25825
      database: AUTOMATION_TESTING
      password: Tushar12345678
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 1
      type: snowflake
      user: AB2
      warehouse: COMPUTE_WH
  target: dev
